In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("LHE_keyframe_to_time_mapping.csv")
df.head()

  video_id  keyframe_id  timeframe
0    LHE01            0   0.000000
1    LHE01          250   4.170833
2    LHE01          500   8.341667
3    LHE01          671  11.194517
4    LHE01          921  15.365350

In [3]:
df['id'] = df.index + 1
df['image_id'] = df.apply(lambda row: f"LHE/{row['video_id']}/{row['keyframe_id']}", axis=1)
df['start_time'] = df['timeframe']
df['end_time'] = df['timeframe']
df = df[['id', 'image_id', 'video_id', 'keyframe_id', 'start_time', 'end_time']]
df.head()

   id       image_id video_id  keyframe_id  start_time   end_time
0   1    LHE/LHE01/0    LHE01            0    0.000000   0.000000
1   2  LHE/LHE01/250    LHE01          250    4.170833   4.170833
2   3  LHE/LHE01/500    LHE01          500    8.341667   8.341667
3   4  LHE/LHE01/671    LHE01          671   11.194517  11.194517
4   5  LHE/LHE01/921    LHE01          921   15.365350  15.365350

In [4]:
df.to_csv("./metadata_v1.csv", index=False)