In [5]:
import pandas as pd

In [6]:

df = pd.read_csv("./metadata_v1.csv")
df.head()

   id                   image_id  video_id  start_time  end_time
0   1  V3C/00001/shot00001_1_RKF         1        0.00      5.08
1   2  V3C/00001/shot00001_2_RKF         1        5.12      5.32
2   3  V3C/00001/shot00001_3_RKF         1        5.36      5.84
3   4  V3C/00001/shot00001_4_RKF         1        5.88      6.28
4   5  V3C/00001/shot00001_5_RKF         1        6.32      7.96

In [3]:
# add "V3C/" to the beginning of each value in the "image_id" column
df["image_id"] = "V3C/" + df["image_id"].astype(str)
df.head()

   id                   image_id  video_id  start_time  end_time
0   1  V3C/00001/shot00001_1_RKF         1        0.00      5.08
1   2  V3C/00001/shot00001_2_RKF         1        5.12      5.32
2   3  V3C/00001/shot00001_3_RKF         1        5.36      5.84
3   4  V3C/00001/shot00001_4_RKF         1        5.88      6.28
4   5  V3C/00001/shot00001_5_RKF         1        6.32      7.96

In [4]:
# save the updated dataframe to a new CSV file
df.to_csv("./metadata_v1.csv", index=False)

### Add OCR

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./metadata_v1.csv")
df.head()

   id                   image_id  video_id  start_time  end_time
0   1  V3C/00001/shot00001_1_RKF         1        0.00      5.08
1   2  V3C/00001/shot00001_2_RKF         1        5.12      5.32
2   3  V3C/00001/shot00001_3_RKF         1        5.36      5.84
3   4  V3C/00001/shot00001_4_RKF         1        5.88      6.28
4   5  V3C/00001/shot00001_5_RKF         1        6.32      7.96

In [ ]:
# for each row, map the image_id to the link of a json path containing ocr results and set the ocr text to column 'ocr'
import os
import json

def get_ocr_text(image_id):
    json_path = os.path.join("/home/hlmquan/LSC24_SemanticSearchWebApp/backend_update/data/vbs25_v3c/ocr", image_id.replace("V3C/", "") + ".json")
    if os.path.exists(json_path):
        with open(json_path, "r") as f:
            data = json.load(f)
            rec_texts = data["rec_texts"]
            return " ".join(rec_texts)
    else:
        return ""
    

df["ocr"] = df["image_id"].apply(get_ocr_text)
df.head()

   id                   image_id  video_id  start_time  end_time ocr
0   1  V3C/00001/shot00001_1_RKF         1        0.00      5.08
1   2  V3C/00001/shot00001_2_RKF         1        5.12      5.32
2   3  V3C/00001/shot00001_3_RKF         1        5.36      5.84
3   4  V3C/00001/shot00001_4_RKF         1        5.88      6.28
4   5  V3C/00001/shot00001_5_RKF         1        6.32      7.96

In [5]:
df.sample(20)

,id,image_id,video_id,start_time,end_time,ocr
3436792,3436793,V3C/23685/shot23685_262_RKF,23685,206.406,206.706,
10839,10840,V3C/00087/shot00087_280_RKF,87,237.779,238.446,
2587174,2587175,V3C/17787/shot17787_5_RKF,17787,13.040,16.680,
2399034,2399035,V3C/16445/shot16445_98_RKF,16445,89.480,91.160,
2402388,2402389,V3C/16464/shot16464_119_RKF,16464,279.960,282.840,
571480,571481,V3C/03997/shot03997_355_RKF,3997,1834.465,1840.572,
1338112,1338113,V3C/09122/shot09122_31_RKF,9122,94.320,100.480,
1076972,1076973,V3C/07434/shot07434_1412_RKF,7434,979.200,979.920,
1474962,1474963,V3C/10102/shot10102_65_RKF,10102,320.987,322.071,
3461672,3461673,V3C/23877/shot23877_178_RKF,23877,128.044,128.336,
1847037,1847038,V3C/12716/shot12716_331_RKF,12716,352.040,352.760,
1089099,1089100,V3C/07524/shot07524_127_RKF,7524,233.566,235.151,
3182597,3182598,V3C/21949/shot21949_11_RKF,21949,40.607,43.910,
164539,164540,V3C/01168/shot01168_17_RKF,1168,28.800,31.080,
821799,821800,V3C/05705/shot05705_22_RKF,5705,23.760,25.440,
441087,441088,V3C/03102/shot03102_144_RKF,3102,166.249,167.959,
3045150,3045151,V3C/21012/shot21012_204_RKF,21012,810.040,813.000,
1911359,1911360,V3C/13193/shot13193_231_RKF,13193,778.680,781.080,
3404337,3404338,V3C/23459/shot23459_46_RKF,23459,198.960,199.360,
3669645,3669646,V3C/25275/shot25275_59_RKF,25275,100.033,100.266,

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./metadata_v2.csv")

/tmp/ipykernel_2348507/2934798907.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("./metadata_v2.csv")

In [3]:
len(df)

4143682

In [10]:
# get 'ocr' unique values
ocr_values = df['ocr'].unique()
# which is the most frequent
ocr_counts = df['ocr'].value_counts()

# print NaN values count
nan_count = df['ocr'].isna().sum()
print(f"NaN values count: {nan_count}")

NaN values count: 3231261

In [11]:
# use pd.isna to find NaN values in 'ocr' column
nan_ocr = df[pd.isna(df['ocr'])]
nan_ocr

,id,image_id,video_id,start_time,end_time,ocr
0,1,V3C/00001/shot00001_1_RKF,1,0.00,5.08,NaN
1,2,V3C/00001/shot00001_2_RKF,1,5.12,5.32,NaN
2,3,V3C/00001/shot00001_3_RKF,1,5.36,5.84,NaN
3,4,V3C/00001/shot00001_4_RKF,1,5.88,6.28,NaN
4,5,V3C/00001/shot00001_5_RKF,1,6.32,7.96,NaN
...,...,...,...,...,...,...
4143677,4143678,V3C/28450/shot28450_151_RKF,28450,496.00,498.32,NaN
4143678,4143679,V3C/28450/shot28450_152_RKF,28450,498.36,498.48,NaN
4143679,4143680,V3C/28450/shot28450_153_RKF,28450,498.52,503.24,NaN
4143680,4143681,V3C/28450/shot28450_154_RKF,28450,503.28,503.36,NaN
4143681,4143682,V3C/28450/shot28450_155_RKF,28450,503.40,516.56,NaN

In [13]:
pd.isna(df['ocr']).sum()

3231261

In [9]:
# number of rows with non-empty ocr
len(df[df["ocr"].notnull() & (df["ocr"] != "")])

912421

In [11]:
df.sample(10)

,id,image_id,video_id,start_time,end_time,ocr
2608847,2608848,V3C/17943/shot17943_298_RKF,17943,943.575,952.418,NaN
1695925,1695926,V3C/11636/shot11636_3_RKF,11636,42.160,53.760,NaN
1683217,1683218,V3C/11554/shot11554_136_RKF,11554,196.600,198.200,NaN
1158078,1158079,V3C/07929/shot07929_1634_RKF,7929,2177.560,2178.160,NaN
3404928,3404929,V3C/23465/shot23465_81_RKF,23465,289.172,291.190,NaN
1191736,1191737,V3C/08108/shot08108_18_RKF,8108,131.714,132.549,NaN
498467,498468,V3C/03514/shot03514_5_RKF,3514,2.966,4.300,NaN
3269039,3269040,V3C/22514/shot22514_315_RKF,22514,199.240,199.920,NaN
673437,673438,V3C/04683/shot04683_659_RKF,4683,869.668,870.903,NaN
3153431,3153432,V3C/21752/shot21752_25_RKF,21752,54.854,59.559,NaN