In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('metadata_v6.csv')

In [4]:
df.head()

,image_id,id,utc_date,utc_time,timezone,local_date,local_time,day_of_week,new_lat,new_lng,...,location_displayed,location_id,event_id,caption,ocr,object_tags,video_id,image_available,activity,context_id
0,201901/01/20190101_103717_000,1,2019-01-01,10:37:17,Europe/Dublin,2019-01-01,10:37:17,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,0,a window with curtains and a picture of a chair,'口',"curtain,house,bed",20190101,1,unknown,20190101_5
1,201901/01/20190101_103749_000,2,2019-01-01,10:37:49,Europe/Dublin,2019-01-01,10:37:49,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,0,a cabinet with a shelf and a mirror on it,No OCR,"house,cup",20190101,1,walking indoor,20190101_5
2,201901/01/20190101_103821_000,3,2019-01-01,10:38:21,Europe/Dublin,2019-01-01,10:38:21,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,1,a window with a view of a house in the backgro...,No OCR,"window,house",20190101,1,unknown,20190101_5
3,201901/01/20190101_103853_000,4,2019-01-01,10:38:53,Europe/Dublin,2019-01-01,10:38:53,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,2,a kitchen with a skylight and a bowl of fruit.,No OCR,"human face,girl,dining table,bottle,clothing,p...",20190101,1,unknown,20190101_5
4,201901/01/20190101_103925_000,5,2019-01-01,10:39:25,Europe/Dublin,2019-01-01,10:39:25,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,3,a computer monitor sitting on top of a desk.,No OCR,"computer keyboard,keyboard,mouse,laptop,tv,book",20190101,1,using a computer,20190101_5

In [11]:
# read this file
# /home/hlmquan/LSC24_SemanticSearchWebApp/backend_update/database/color/color_output.db
import sqlite3

# to csv
conn = sqlite3.connect('/home/hlmquan/LSC24_SemanticSearchWebApp/backend_update/database/color/color_output.db')

# find table name
# table name 'color_detection'
table_name = 'color_detection'
df_color = pd.read_sql_query(f'SELECT * FROM {table_name}', conn)
df_color.to_csv('color_detection.csv', index=False)
df_color['image_id'] = df_color['image_id'].apply(lambda x: f"{x[:6]}/{x[6:8]}/{x}")
df_color.head()

,image_id,color
0,201901/01/20190101_103717_000,Black Blue Brown Gray Skin White
1,201901/01/20190101_103749_000,Black Blue Brown Gray Skin White
2,201901/01/20190101_103821_000,Black Blue Brown Gray Skin White
3,201901/01/20190101_103853_000,Black Blue Brown Gray Green Orange Purple Red ...
4,201901/01/20190101_103925_000,Black Blue Brown Gray Skin White

In [13]:
# add to metadata_v6.csv (df)
df_merged = pd.merge(df, df_color, on=['image_id'], how='left')
df_merged.head()

,image_id,id,utc_date,utc_time,timezone,local_date,local_time,day_of_week,new_lat,new_lng,...,location_id,event_id,caption,ocr,object_tags,video_id,image_available,activity,context_id,color
0,201901/01/20190101_103717_000,1,2019-01-01,10:37:17,Europe/Dublin,2019-01-01,10:37:17,Tuesday,53.38998,-6.14576,...,0,0,a window with curtains and a picture of a chair,'口',"curtain,house,bed",20190101,1,unknown,20190101_5,Black Blue Brown Gray Skin White
1,201901/01/20190101_103749_000,2,2019-01-01,10:37:49,Europe/Dublin,2019-01-01,10:37:49,Tuesday,53.38998,-6.14576,...,0,0,a cabinet with a shelf and a mirror on it,No OCR,"house,cup",20190101,1,walking indoor,20190101_5,Black Blue Brown Gray Skin White
2,201901/01/20190101_103821_000,3,2019-01-01,10:38:21,Europe/Dublin,2019-01-01,10:38:21,Tuesday,53.38998,-6.14576,...,0,1,a window with a view of a house in the backgro...,No OCR,"window,house",20190101,1,unknown,20190101_5,Black Blue Brown Gray Skin White
3,201901/01/20190101_103853_000,4,2019-01-01,10:38:53,Europe/Dublin,2019-01-01,10:38:53,Tuesday,53.38998,-6.14576,...,0,2,a kitchen with a skylight and a bowl of fruit.,No OCR,"human face,girl,dining table,bottle,clothing,p...",20190101,1,unknown,20190101_5,Black Blue Brown Gray Green Orange Purple Red ...
4,201901/01/20190101_103925_000,5,2019-01-01,10:39:25,Europe/Dublin,2019-01-01,10:39:25,Tuesday,53.38998,-6.14576,...,0,3,a computer monitor sitting on top of a desk.,No OCR,"computer keyboard,keyboard,mouse,laptop,tv,book",20190101,1,using a computer,20190101_5,Black Blue Brown Gray Skin White

In [14]:
len(df_merged)

725949

In [15]:
df_merged.to_csv('metadata_v7.csv', index=False)