In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('metadata_v6.csv')

In [5]:
df.head()

,image_id,id,utc_date,utc_time,timezone,local_date,local_time,day_of_week,new_lat,new_lng,location,location_displayed,location_id,event_id,caption,ocr,object_tags,video_id,image_available,activity
0,201901/01/20190101_103717_000,1,2019-01-01,10:37:17,Europe/Dublin,2019-01-01,10:37:17,Tuesday,53.38998,-6.14576,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,0,a window with curtains and a picture of a chair,'口',"curtain,house,bed",20190101,1,unknown
1,201901/01/20190101_103749_000,2,2019-01-01,10:37:49,Europe/Dublin,2019-01-01,10:37:49,Tuesday,53.38998,-6.14576,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,0,a cabinet with a shelf and a mirror on it,No OCR,"house,cup",20190101,1,walking indoor
2,201901/01/20190101_103821_000,3,2019-01-01,10:38:21,Europe/Dublin,2019-01-01,10:38:21,Tuesday,53.38998,-6.14576,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,1,a window with a view of a house in the backgro...,No OCR,"window,house",20190101,1,unknown
3,201901/01/20190101_103853_000,4,2019-01-01,10:38:53,Europe/Dublin,2019-01-01,10:38:53,Tuesday,53.38998,-6.14576,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,2,a kitchen with a skylight and a bowl of fruit.,No OCR,"human face,girl,dining table,bottle,clothing,p...",20190101,1,unknown
4,201901/01/20190101_103925_000,5,2019-01-01,10:39:25,Europe/Dublin,2019-01-01,10:39:25,Tuesday,53.38998,-6.14576,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,3,a computer monitor sitting on top of a desk.,No OCR,"computer keyboard,keyboard,mouse,laptop,tv,book",20190101,1,using a computer

In [11]:
def image_id_to_context_id(image_id):
    image_id = image_id.split('/')[-1]
    # return image_id[:11] + '_' + ('0' if image_id[11] < '3' else '1')
    return image_id[:8] + '_' + str(int(image_id[9:11]) // 2)

df['context_id'] = df['image_id'].apply(image_id_to_context_id)

# random print
df.sample(5)

,image_id,id,utc_date,utc_time,timezone,local_date,local_time,day_of_week,new_lat,new_lng,...,location_displayed,location_id,event_id,caption,ocr,object_tags,video_id,image_available,activity,context_id
527948,202001/06/20200106_085628_000,527949,2020-01-06,08:56:28,Asia/Seoul,2020-01-06,17:56:28,Monday,36.368868,127.362850,...,"Korea Institute of Science and Technology, Dae...",7421,299,a man standing in front of a computer with a r...,No OCR,"remote,clothing,person,tv,backpack,building,ma...",20200106,1,attending a presentation,20200106_4
591113,202003/16/20200316_120508_000,591114,2020-03-16,12:05:08,Europe/Dublin,2020-03-16,12:05:08,Monday,53.385719,-6.257691,...,"Dublin City University (DCU), Dublin, Ireland,...",8343,345,a computer monitor sitting on top of a desk.,No OCR,"computer monitor,desk,bottle,remote,tv,bowl",20200316,1,using a computer,20200316_6
132914,201904/11/20190411_214509_000,132915,2019-04-11,21:45:09,Europe/Dublin,2019-04-11,22:45:09,Thursday,53.389808,-6.149539,...,"Donaghmede Shopping Centre, Dublin, Ireland, L...",1948,300,a person holding a cell phone in their hand.,No OCR,"umbrella,person,laptop,tv,bowl,book,apple,chai...",20190411,1,using a mobile device,20190411_10
46232,201902/03/20190203_141433_000,46233,2019-02-03,14:14:33,Europe/Dublin,2019-02-03,14:14:33,Sunday,53.389969,-6.145653,...,"HOME, Dublin, Ireland, Leinster",731,187,a man standing in a kitchen preparing food.,No OCR,"bottle,cup,clothing,person,spoon,bowl,refriger...",20190203,1,preparing some food,20190203_7
348325,201909/12/20190912_192057_000,348326,2019-09-12,19:20:57,Europe/Dublin,2019-09-12,20:20:57,Thursday,53.389977,-6.145798,...,"Car, Dublin, Ireland, Leinster",5296,392,a car's steering wheel and a street light,No OCR,cup,20190912,1,driving,20190912_9

In [12]:
df.to_csv('metadata_v6.csv', index=False)

In [10]:
df = pd.read_csv('metadata_v6.csv')
df.head()

,image_id,id,utc_date,utc_time,timezone,local_date,local_time,day_of_week,new_lat,new_lng,...,location_displayed,location_id,event_id,caption,ocr,object_tags,video_id,image_available,activity,context_id
0,201901/01/20190101_103717_000,1,2019-01-01,10:37:17,Europe/Dublin,2019-01-01,10:37:17,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,0,a window with curtains and a picture of a chair,'口',"curtain,house,bed",20190101,1,unknown,20190101_10_1
1,201901/01/20190101_103749_000,2,2019-01-01,10:37:49,Europe/Dublin,2019-01-01,10:37:49,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,0,a cabinet with a shelf and a mirror on it,No OCR,"house,cup",20190101,1,walking indoor,20190101_10_1
2,201901/01/20190101_103821_000,3,2019-01-01,10:38:21,Europe/Dublin,2019-01-01,10:38:21,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,1,a window with a view of a house in the backgro...,No OCR,"window,house",20190101,1,unknown,20190101_10_1
3,201901/01/20190101_103853_000,4,2019-01-01,10:38:53,Europe/Dublin,2019-01-01,10:38:53,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,2,a kitchen with a skylight and a bowl of fruit.,No OCR,"human face,girl,dining table,bottle,clothing,p...",20190101,1,unknown,20190101_10_1
4,201901/01/20190101_103925_000,5,2019-01-01,10:39:25,Europe/Dublin,2019-01-01,10:39:25,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,3,a computer monitor sitting on top of a desk.,No OCR,"computer keyboard,keyboard,mouse,laptop,tv,book",20190101,1,using a computer,20190101_10_1